name: Publish Package

on:
  release:
    types: [published]
    paths-ignore:
      - .gitignore
      - LICENSE.md
      - README.md

jobs:
  PyPi:
    runs-on: ubuntu-latest
    container: python:3.9-slim-buster
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          python3 -m pip install --upgrade build
          python3 -m build
      
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}