
name: "Tests"
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

    branches:
      - master
    tags:
      - ci
      - tests  
    paths-ignore:
      - .gitignore
      - LICENSE.md
      - README.md

  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - LICENSE.md
      - README.md

env:
  PYTEST_ADDOPTS: --color=yes

jobs:
  precommit:
    runs-on: ubuntu-latest
    container: bitnami/git:2.35.1
    steps:
      - uses: actions/checkout@v3
      - name: Hooks
        shell: bash
        run: |
          apt-get -y update
          apt-get -y install --no-install-recommends python3-pip
          python3 -m pip install pre-commit

          pre-commit install
          pre-commit run --all-files

  tests:
    needs: precommit
    runs-on: ubuntu-latest
    container: python:3.9-slim-buster
    steps:
      - uses: actions/checkout@v3

      - name: Tests
        id: pytest
        shell: bash
        run: |
          python3 -m pip install .
          pytest -vv tests